from datetime import datetime, timezone
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.database import async_session
from app.models.db_models import LLMModel, ModelPricing


SEED_MODELS = [
    {
        "provider_name": "anthropic",
        "model_name": "claude-3-5-haiku-20241022",
        "display_name": "Claude 3.5 Haiku",
        "tier": "tier1",
        "context_window": 200000,
        "supports_tools": True,
        "supports_json": True,
        "supports_streaming": True,
        "supports_prompt_cache": True,
        "base_quality_score": 0.82,
        "expected_latency_ms": 400,
        "input_price_per_million": 0.80,
        "output_price_per_million": 4.00,
        "cached_input_price_per_million": 0.08,
    },
    {
        "provider_name": "anthropic",
        "model_name": "claude-3-5-sonnet-20241022",
        "display_name": "Claude 3.5 Sonnet",
        "tier": "tier2",
        "context_window": 200000,
        "supports_tools": True,
        "supports_json": True,
        "supports_streaming": True,
        "supports_prompt_cache": True,
        "base_quality_score": 0.95,
        "expected_latency_ms": 1200,
        "input_price_per_million": 3.00,
        "output_price_per_million": 15.00,
        "cached_input_price_per_million": 0.30,
    },
    {
        "provider_name": "gemini",
        "model_name": "models/gemini-2.5-flash",
        "display_name": "Gemini 2.5 Flash",
        "tier": "tier1",
        "context_window": 1000000,
        "supports_tools": True,
        "supports_json": True,
        "supports_streaming": True,
        "supports_prompt_cache": False,
        "base_quality_score": 0.85,
        "expected_latency_ms": 300,
        "input_price_per_million": 0.075,
        "output_price_per_million": 0.30,
        "cached_input_price_per_million": 0.0,
    },
    {
        "provider_name": "gemini",
        "model_name": "models/gemini-2.5-flash",
        "display_name": "Gemini 2.5 Flash (Deep Synthesis)",
        "tier": "tier2",
        "context_window": 1000000,
        "supports_tools": True,
        "supports_json": True,
        "supports_streaming": True,
        "supports_prompt_cache": False,
        "base_quality_score": 0.90,
        "expected_latency_ms": 800,
        "input_price_per_million": 0.075,
        "output_price_per_million": 0.30,
        "cached_input_price_per_million": 0.0,
    },
    {
        "provider_name": "groq",
        "model_name": "llama-3.1-8b-instant",
        "display_name": "Llama 3.1 8B Instant",
        "tier": "tier1",
        "context_window": 128000,
        "supports_tools": True,
        "supports_json": True,
        "supports_streaming": True,
        "supports_prompt_cache": False,
        "base_quality_score": 0.78,
        "expected_latency_ms": 150,
        "input_price_per_million": 0.05,
        "output_price_per_million": 0.08,
        "cached_input_price_per_million": 0.0,
    },
    {
        "provider_name": "groq",
        "model_name": "llama-3.3-70b-versatile",
        "display_name": "Llama 3.3 70B Versatile",
        "tier": "tier2",
        "context_window": 128000,
        "supports_tools": True,
        "supports_json": True,
        "supports_streaming": True,
        "supports_prompt_cache": False,
        "base_quality_score": 0.88,
        "expected_latency_ms": 500,
        "input_price_per_million": 0.59,
        "output_price_per_million": 0.79,
        "cached_input_price_per_million": 0.0,
    },
    {
        "provider_name": "mistral",
        "model_name": "mistral-small-latest",
        "display_name": "Mistral Small",
        "tier": "tier1",
        "context_window": 128000,
        "supports_tools": True,
        "supports_json": True,
        "supports_streaming": True,
        "supports_prompt_cache": False,
        "base_quality_score": 0.80,
        "expected_latency_ms": 350,
        "input_price_per_million": 0.20,
        "output_price_per_million": 0.60,
        "cached_input_price_per_million": 0.0,
    },
    {
        "provider_name": "mistral",
        "model_name": "mistral-large-latest",
        "display_name": "Mistral Large",
        "tier": "tier2",
        "context_window": 128000,
        "supports_tools": True,
        "supports_json": True,
        "supports_streaming": True,
        "supports_prompt_cache": False,
        "base_quality_score": 0.91,
        "expected_latency_ms": 900,
        "input_price_per_million": 2.00,
        "output_price_per_million": 6.00,
        "cached_input_price_per_million": 0.0,
    },
    {
        "provider_name": "openai",
        "model_name": "gpt-4o-mini",
        "display_name": "GPT-4o-mini",
        "tier": "tier1",
        "context_window": 128000,
        "supports_tools": True,
        "supports_json": True,
        "supports_streaming": True,
        "supports_prompt_cache": True,
        "base_quality_score": 0.83,
        "expected_latency_ms": 350,
        "input_price_per_million": 0.15,
        "output_price_per_million": 0.60,
        "cached_input_price_per_million": 0.075,
    },
    {
        "provider_name": "openai",
        "model_name": "gpt-4o",
        "display_name": "GPT-4o",
        "tier": "tier2",
        "context_window": 128000,
        "supports_tools": True,
        "supports_json": True,
        "supports_streaming": True,
        "supports_prompt_cache": True,
        "base_quality_score": 0.94,
        "expected_latency_ms": 800,
        "input_price_per_million": 2.50,
        "output_price_per_million": 10.00,
        "cached_input_price_per_million": 1.25,
    },
    {
        "provider_name": "mock",
        "model_name": "claude-3-5-haiku-20241022",
        "display_name": "Claude 3.5 Haiku (Simulated)",
        "tier": "tier1",
        "context_window": 200000,
        "supports_tools": False,
        "supports_json": True,
        "supports_streaming": False,
        "supports_prompt_cache": False,
        "base_quality_score": 0.82,
        "expected_latency_ms": 50,
        "input_price_per_million": 0.80,
        "output_price_per_million": 4.00,
        "cached_input_price_per_million": 0.0,
    },
    {
        "provider_name": "mock",
        "model_name": "claude-3-5-sonnet-20241022",
        "display_name": "Claude 3.5 Sonnet (Simulated)",
        "tier": "tier2",
        "context_window": 200000,
        "supports_tools": False,
        "supports_json": True,
        "supports_streaming": False,
        "supports_prompt_cache": False,
        "base_quality_score": 0.95,
        "expected_latency_ms": 100,
        "input_price_per_million": 3.00,
        "output_price_per_million": 15.00,
        "cached_input_price_per_million": 0.0,
    },
]


async def seed_if_empty():
    async with async_session() as session:
        result = await session.execute(select(LLMModel).limit(1))
        if result.scalars().first() is not None:
            return

        now = datetime.now(timezone.utc)
        for data in SEED_MODELS:
            model = LLMModel(
                provider_name=data["provider_name"],
                model_name=data["model_name"],
                display_name=data["display_name"],
                tier=data["tier"],
                active=True,
                context_window=data["context_window"],
                supports_tools=data["supports_tools"],
                supports_json=data["supports_json"],
                supports_streaming=data["supports_streaming"],
                supports_prompt_cache=data["supports_prompt_cache"],
                base_quality_score=data["base_quality_score"],
                expected_latency_ms=data["expected_latency_ms"],
            )
            session.add(model)
            await session.flush()

            pricing = ModelPricing(
                model_id=model.id,
                input_price_per_million=data["input_price_per_million"],
                output_price_per_million=data["output_price_per_million"],
                cached_input_price_per_million=data["cached_input_price_per_million"],
                currency="USD",
                effective_from=now,
                effective_to=None,
            )
            session.add(pricing)

        await session.commit()
